name: Release
on:
    pull_request:
      branches: main
      types: closed

jobs:
  release:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Release
        uses: huggingface/semver-release-action@latest