name: Block merges from not allowed branches

on:
  pull_request:

jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        if: github.base_ref == 'main' && github.head_ref != 'dev' && startsWith(github.head_ref, 'hotfix/') == false
        run: |
          echo "ERROR: You can only merge to main from dev or a hotfix branch."
          exit 1