name: Deployment on Testing

on:
  pull_request:
    branches: test
    types: closed

jobs:
  deployment:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    environment: testing
    steps:
    - run: |
        echo Deployed on test server