name: Unit Tests

on:
  pull_request

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Miniconda with Mamba
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.12
        activate-environment: test-env
        environment-file: environment.yml
        use-mamba: true

    - name: Initialize conda shell
      shell: bash -l {0}
      run: |
        conda init bash
        source ~/.bashrc
        conda activate test-env

    - name: Run tests with coverage
      shell: bash -l {0}
      env:
        PYTHONPATH: .
      run: |
        mkdir logs logs/analysis logs/upload logs/download logs/errors logs/cleanup logs/debugging
        conda activate test-env
        pytest